# Generated by Django 3.2.8 on 2021-10-28 00:07

from django.db import migrations

def cargar_categorias(apps, schema_editor):
    Categoria = apps.get_model("posts", "Categoria")
    categorias = [
        ('Cocina', 'Cocina'),
        ('Plomería', 'Plomería'),
        ('Vehículos', 'Vehículos'),
        ('Música', 'Música'),
        ('Ciencia', 'Ciencia'),
        ('Ocio', 'Ocio'),
        ('Deportes', 'Deportes'),
        ('Indumentaria', 'Indumentaria'),
        ('Manualidades', 'Manualidades'),
        ('Jardinería', 'Jardinería'),
        ('Fitness', 'Fitness'),
        ('Arte', 'Arte'),
        ('Hogar', 'Hogar'),
        ('Deco', 'Deco'),
        ('Hazlo-tu-mismo', 'Hazlo-tu-mismo'),
        ('Life hacks', 'Life hacks'),
        ('Salud', 'Salud'),
        ('Entretenimiento', 'Entretenimiento'),
        ('Carpintería', 'Carpintería'),
        ('Tecnología', 'Tecnología'),
        ('Gaming', 'Gaming'),
        ('Humor', 'Humor'),
        ('Albañilería', 'Albañilería'),
        ('Finanzas/economía', 'Finanzas/economía'),
    ]
    for titulo, descripcion in categorias:
        Categoria.objects.get_or_create(titulo=titulo, descripcion=descripcion)


def eliminar_categorias(apps, schema_editor):
    Categoria = apps.get_model("posts", "Categoria")
    Categoria.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comentario'),
    ]

    operations = [
        migrations.RunPython(cargar_categorias, eliminar_categorias),
    ]
