# Generated by Django 3.2.8 on 2021-10-27 02:22

from django.db import migrations


def cargar_avatars(apps, schema_editor):
    """
    Genera la carga inicial de avatars para los usuarios
    """
    Avatar = apps.get_model('users', 'Avatar')
    Avatar.objects.get_or_create(nombre_imagen='Batman2.png', nombre_a_mostrar='Batman rojo', descripcion='Batman con detalles en rojo.')
    Avatar.objects.get_or_create(nombre_imagen='CARP-incho.png', nombre_a_mostrar='CARP-incho', descripcion='Carpincho con remera de River Plate.')
    Avatar.objects.get_or_create(nombre_imagen='Lentes.png', nombre_a_mostrar='Carpincho con lentes', descripcion='Carpincho con lentes.')
    Avatar.objects.get_or_create(nombre_imagen='Matero.png', nombre_a_mostrar='Carpincho matero', descripcion='Carpincho sosteniendo un mate argentino.')
    Avatar.objects.get_or_create(nombre_imagen='Motoquero.png', nombre_a_mostrar='Carpincho motoquero', descripcion='Carpincho con casco subido a una moto.')
    Avatar.objects.get_or_create(nombre_imagen='Traje.png', nombre_a_mostrar='Carpincho con traje', descripcion='Carpincho con traje.')


def eliminar_avatars(apps, schema_editor):
    """
    Elimina todos los avatars, se ejecuta al deshacer la migración
    """
    Avatar = apps.get_model('users', 'Avatar')
    Avatar.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211005_2238'),
    ]

    operations = [
        migrations.RunPython(cargar_avatars, eliminar_avatars),
    ]
