# Generated by Django 3.2.9 on 2021-11-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_carga_avatars'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nivel',
            field=models.IntegerField(choices=[(0, 'sin premium'), (1, 'premium basico'), (2, 'premium medio'), (3, 'premium avanzado')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ranking',
            field=models.IntegerField(blank=True, choices=[(0, 'bronce'), (1, 'plata'), (2, 'oro')], null=True),
        ),
    ]
