# Generated by Django 3.2.9 on 2021-11-12 15:21

from django.db import migrations


def cargar_avatars_premium(apps, schema_editor):
    """
    Genera la carga de los primeros avatars premium
    """
    Avatar = apps.get_model('users', 'Avatar')
    Avatar.objects.get_or_create(nombre_imagen='Lluvia.png', nombre_a_mostrar='Carpincho lluvia', descripcion='Carpincho con paraguas bajo la lluvia.', nivel=1)
    Avatar.objects.get_or_create(nombre_imagen='Furia.png', nombre_a_mostrar='Carpincho enojado', descripcion='Carpincho furioso.', nivel=2)
    Avatar.objects.get_or_create(nombre_imagen='Fiesta.png', nombre_a_mostrar='Carpincho fiesta', descripcion='Carpincho con clobo, sombrerito y guirnaldas.', nivel=3)


def eliminar_avatars_premium(apps, schema_editor):
    """
    Elimina todos los avatars premium
    """
    Avatar = apps.get_model('users', 'Avatar')
    Avatar.objects.filter(nivel__gt=0).delete()


class Migration(migrations.Migration):
    
    dependencies = [
        ('users', '0007_avatar_nivel'),
    ]

    operations = [
        migrations.RunPython(cargar_avatars_premium, eliminar_avatars_premium),
    ]
